# Generated by Django 5.2.15 on 2026-07-28 10:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO description')),
                ('seo_h1', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO H1')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('short_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Короткий опис')),
                ('body', tinymce.models.HTMLField(blank=True, default='', verbose_name='Опис')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('cta_label', models.CharField(blank=True, default='Замовити', max_length=120, verbose_name='CTA')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'db_table': 'services_service',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='services_se_is_publ_93e246_idx')],
            },
        ),
    ]
