# Generated by Django 5.2.15 on 2026-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_deliverables_service_expected_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Крок процесу',
                'verbose_name_plural': 'Кроки процесу',
                'db_table': 'services_process_step',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
