# Generated by Django 5.2.15 on 2026-07-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('consent', models.BooleanField(default=False, verbose_name='Згода GDPR')),
                ('source', models.CharField(choices=[('home', 'Головна'), ('hero', 'Hero'), ('service', 'Послуга'), ('contacts', 'Контакти')], default='home', max_length=32, verbose_name='Джерело')),
                ('source_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL джерела')),
                ('status', models.CharField(choices=[('new', 'Новий лід'), ('in_progress', 'В обробці'), ('closed', 'Закрито'), ('spam', 'Спам')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('crm_external_id', models.CharField(blank=True, default='', max_length=64, verbose_name='CRM ID')),
                ('crm_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='CRM sync')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'leads_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx'), models.Index(fields=['is_read'], name='leads_lead_is_read_16e1bd_idx')],
            },
        ),
    ]
