# Generated by Django 5.2.15 on 2026-07-28 10:06

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
                'db_table': 'blog_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO description')),
                ('seo_h1', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO H1')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.CharField(blank=True, default='', max_length=500, verbose_name='Анонс')),
                ('body', tinymce.models.HTMLField(blank=True, default='', verbose_name='Контент')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обкладинка')),
                ('cover_alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt обкладинки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Запис блогу',
                'verbose_name_plural': 'Записи блогу',
                'db_table': 'blog_post',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='blog_post_is_publ_9ad937_idx'), models.Index(fields=['category', '-published_at'], name='blog_post_categor_cb6e5f_idx')],
            },
        ),
    ]
