# Generated by Django 5.2.15 on 2026-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_featured'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_is_feat_7251c7_idx',
            old_name='blog_post_is_feat_7c2a1e_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Формат: JPG, PNG або WebP. Рекомендований розмір 960×540 px (співвідношення 16:9). Мінімум 640×360 px. Файл до 1 МБ. Інакше зображення обріжеться або розтягне верстку.', null=True, upload_to='blog/', verbose_name='Обкладинка'),
        ),
    ]
