# Generated by Django 5.2.15 on 2026-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect301',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('old_path', models.CharField(max_length=255, unique=True, verbose_name='Старий шлях')),
                ('new_path', models.CharField(max_length=255, verbose_name='Новий шлях')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '301 редірект',
                'verbose_name_plural': '301 редіректи',
                'db_table': 'seo_redirect_301',
                'ordering': ['old_path'],
            },
        ),
    ]
