# Generated by Django 5.2.15 on 2026-07-28 10:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('headline', models.CharField(max_length=255, verbose_name='H1')),
                ('subheadline', models.TextField(blank=True, default='', verbose_name='Підзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Зображення 21:9')),
                ('image_alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt')),
                ('cta_label', models.CharField(default='Залишити заявку', max_length=120, verbose_name='CTA текст')),
                ('cta_target', models.CharField(default='#lead-form', help_text='#lead-form або modal:lead', max_length=64, verbose_name='CTA ціль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Hero головної',
                'verbose_name_plural': 'Hero головної',
                'db_table': 'pages_home_hero',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адреса')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('map_embed_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Embed карти')),
                ('social_links', models.JSONField(blank=True, default=list, verbose_name='Соцмережі')),
                ('robots_extra', models.TextField(blank=True, default='', verbose_name='Доп. robots.txt')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
                'db_table': 'pages_site_settings',
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('block_type', models.CharField(choices=[('services_teaser', 'Превʼю послуг'), ('advantages', 'Чому звертаються'), ('audience', 'Для кого'), ('blog_teaser', 'Превʼю блогу'), ('lead_form', 'Форма заявки')], max_length=32, verbose_name='Тип')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок секції')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимий')),
            ],
            options={
                'verbose_name': 'Блок головної',
                'verbose_name_plural': 'Блоки головної',
                'db_table': 'pages_home_block',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_visible', 'sort_order'], name='pages_home__is_visi_bd2460_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO description')),
                ('seo_h1', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO H1')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', tinymce.models.HTMLField(blank=True, default='', verbose_name='Контент')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Інфо-сторінка',
                'verbose_name_plural': 'Інфо-сторінки',
                'db_table': 'pages_page',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_published', 'slug'], name='pages_page_is_publ_af2dab_idx')],
            },
        ),
    ]
