# Generated by Django 5.2.15 on 2026-07-28 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_work_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Блог — сторінка',
                'verbose_name_plural': 'Блог — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти — сторінка',
                'verbose_name_plural': 'Контакти — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeAdvantagesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeAudienceSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Для кого',
                'verbose_name_plural': 'Головна — Для кого',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBlogSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Блог',
                'verbose_name_plural': 'Головна — Блог',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeLeadSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Заявка',
                'verbose_name_plural': 'Головна — Заявка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeServicesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Послуги',
                'verbose_name_plural': 'Головна — Послуги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — сторінка',
                'verbose_name_plural': 'Послуги — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteBrandSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Бренд / логотипи',
                'verbose_name_plural': 'Бренд / логотипи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFormsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Форми / модалки',
                'verbose_name_plural': 'Форми / модалки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteNavigationSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Навігація',
                'verbose_name_plural': 'Навігація',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ActiveTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Основний (кнопки / акцент)')),
                ('color_primary_hover', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Основний hover')),
                ('color_accent', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Акцент (slate)')),
                ('color_surface', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон сторінки')),
                ('color_text', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Основний текст')),
                ('color_footer', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон футера')),
                ('color_deep', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Глибокий steel (заголовки)')),
                ('color_card', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з tokens.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон карток')),
                ('reset_to_original', models.BooleanField(default=False, help_text='Записує оригінальну бренд-палітру в усі поля.', verbose_name='Повернути до оригіналу')),
                ('clear_to_tokens', models.BooleanField(default=False, help_text='Обнуляє поля; сайт бере значення з tokens.css.', verbose_name='Очистити → tokens.css')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Тема сайту',
                'verbose_name_plural': 'Тема сайту',
                'db_table': 'pages_active_theme',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='pages_active_theme_singleton_id_1')],
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('services', 'Послуги'), ('contacts', 'Контакти'), ('blog', 'Блог')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('label', models.CharField(max_length=128, verbose_name='Підпис')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання')], default='text', max_length=16, verbose_name='Тип')),
                ('text_html', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('link_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL')),
                ('link_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Текст посилання')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'db_table': 'pages_site_block',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
