# Generated by Django 5.2.15 on 2026-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cms_siteblock_theme_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lead_notify_email',
            field=models.EmailField(blank=True, default='', help_text='Куди надсилати заявки з форм. Якщо порожньо — береться ADMIN_NOTIFY_EMAIL з оточення.', max_length=254, verbose_name='Email для заявок'),
        ),
    ]
