# Generated by Django 5.2.15 on 2026-07-28 14:17

import src.pages.favicon_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_lead_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='PNG, ICO або WEBP. Максимум 512 КБ і 512×512 px. Якщо порожньо — використовується стандартна іконка.', null=True, upload_to='brand/favicon/', validators=[src.pages.favicon_validators.validate_favicon_upload], verbose_name='Фавіконка'),
        ),
    ]
