# Generated by Django 5.2.15 on 2026-07-28 14:49

import src.pages.about_hero_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_caption',
            field=models.CharField(blank=True, default='', help_text='Текст на склі поверх фото. Очистіть поле, щоб прибрати підпис.', max_length=160, verbose_name='Підпис на фото'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Формат: JPG, PNG або WebP. Рекомендований розмір 800×1000 px (співвідношення 4:5). Мінімум 480×600 px. Файл до 1 МБ. Відхилення від 4:5 — не більше 10%.', null=True, upload_to='about/', validators=[src.pages.about_hero_validators.validate_about_hero_image], verbose_name='Фото «Про мене»'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_image_alt',
            field=models.CharField(blank=True, default='', help_text='Короткий опис фото для доступності. Якщо порожньо — береться H1.', max_length=255, verbose_name='Alt фото'),
        ),
    ]
