"""Метадані CMS-полів (labels, types, widgets)."""

from typing import Literal

BlockKey = tuple[str, str]
ContentTypeName = Literal['text', 'image', 'url']

BLOCK_FIELD_LABELS: dict[BlockKey, str] = {
    ('home', 'hero_section_visible'): 'Показувати Hero',
    ('home', 'hero_brand'): 'Рядок бренду',
    ('home', 'hero_title'): 'Заголовок H1',
    ('home', 'hero_sub'): 'Підзаголовок',
    ('home', 'hero_image'): 'Фото Hero',
    ('home', 'hero_shade_visible'): 'Затемнення поверх фото',
    ('home', 'hero_cta_label'): 'CTA текст',
    ('home', 'hero_cta_href'): 'CTA посилання',
    ('home', 'hero_secondary_label'): 'Другорядна кнопка',
    ('home', 'hero_secondary_href'): 'Другорядна кнопка — посилання',
    ('home', 'audience_section_visible'): 'Показувати «Для кого»',
    ('home', 'audience_eyebrow'): 'Eyebrow',
    ('home', 'audience_title'): 'Заголовок',
    ('home', 'audience_intro'): 'Вступ',
    ('home', 'audience_cta_text'): 'Текст після лічильника',
    ('home', 'audience_cta_label'): 'Кнопка CTA',
    ('home', 'audience_cta_href'): 'CTA посилання',
    ('home', 'services_section_visible'): 'Показувати послуги',
    ('home', 'services_eyebrow'): 'Eyebrow',
    ('home', 'services_title'): 'Заголовок',
    ('home', 'services_intro'): 'Вступ',
    ('home', 'services_card_more'): 'Текст «Детальніше»',
    ('home', 'services_footer_cta'): 'Кнопка під сіткою',
    ('home', 'services_footer_href'): 'Посилання кнопки',
    ('home', 'advantages_section_visible'): 'Показувати переваги',
    ('home', 'advantages_eyebrow'): 'Eyebrow',
    ('home', 'advantages_title'): 'Заголовок',
    ('home', 'advantages_intro'): 'Вступ',
    ('home', 'advantages_image'): 'Фото під текстом',
    ('home', 'blog_section_visible'): 'Показувати блог',
    ('home', 'blog_eyebrow'): 'Eyebrow',
    ('home', 'blog_title'): 'Заголовок',
    ('home', 'blog_intro'): 'Вступ',
    ('home', 'blog_filter_all'): 'Фільтр: усі',
    ('home', 'blog_filter_cases'): 'Фільтр: кейси',
    ('home', 'blog_filter_news'): 'Фільтр: новини',
    ('home', 'blog_footer_cta'): 'Кнопка під сіткою',
    ('home', 'lead_section_visible'): 'Показувати форму',
    ('home', 'lead_eyebrow'): 'Eyebrow',
    ('home', 'lead_title'): 'Заголовок',
    ('home', 'lead_intro'): 'Вступ',
    ('site', 'brand_name'): 'Назва бренду',
    ('site', 'brand_title'): 'Підпис бренду',
    ('site', 'logo_header'): 'Логотип у шапці',
    ('site', 'logo_footer'): 'Логотип у футері',
    ('site', 'nav_toggle_label'): 'Текст бургер-кнопки',
    ('site', 'nav_open_aria'): 'Aria: відкрити меню',
    ('site', 'nav_aria'): 'Aria: навігація',
    ('site', 'nav_home_label'): 'Головна — текст',
    ('site', 'nav_home_href'): 'Головна — URL',
    ('site', 'nav_about_label'): 'Про мене — текст',
    ('site', 'nav_about_href'): 'Про мене — URL',
    ('site', 'nav_services_label'): 'Послуги — текст',
    ('site', 'nav_services_href'): 'Послуги — URL',
    ('site', 'nav_blog_label'): 'Блог — текст',
    ('site', 'nav_blog_href'): 'Блог — URL',
    ('site', 'nav_contacts_label'): 'Контакти — текст',
    ('site', 'nav_contacts_href'): 'Контакти — URL',
    ('site', 'nav_cta_label'): 'CTA шапки',
    ('site', 'nav_cta_href'): 'CTA шапки — URL',
    ('site', 'nav_home_visible'): 'Показувати «Головна»',
    ('site', 'nav_about_visible'): 'Показувати «Про мене»',
    ('site', 'nav_services_visible'): 'Показувати «Послуги»',
    ('site', 'nav_blog_visible'): 'Показувати «Блог»',
    ('site', 'nav_contacts_visible'): 'Показувати «Контакти»',
    ('site', 'nav_cta_visible'): 'Показувати CTA',
    ('site', 'nav_phone_visible'): 'Показувати телефон',
    ('site', 'footer_tagline'): 'Слоган футера',
    ('site', 'footer_nav_heading'): 'Заголовок навігації',
    ('site', 'footer_contacts_heading'): 'Заголовок контактів',
    ('site', 'footer_messengers_heading'): 'Заголовок месенджерів',
    ('site', 'footer_hours_prefix'): 'Префікс графіка',
    ('site', 'footer_policy_label'): 'Політика — текст',
    ('site', 'footer_policy_href'): 'Політика — URL',
    ('site', 'footer_madeby_label'): 'Кредит розробника',
    ('site', 'footer_madeby_url'): 'URL розробника',
    ('site', 'footer_nav_aria'): 'Aria футер-навігації',
    ('site', 'form_label_name'): 'Лейбл: імʼя',
    ('site', 'form_label_phone'): 'Лейбл: телефон',
    ('site', 'form_label_email'): 'Лейбл: email',
    ('site', 'form_consent_prefix'): 'Текст згоди (до посилання)',
    ('site', 'form_consent_link'): 'Текст посилання на політику',
    ('site', 'form_submit'): 'Кнопка відправки',
    ('site', 'form_success_title'): 'Успіх — заголовок',
    ('site', 'form_success_text'): 'Успіх — текст',
    ('site', 'lead_modal_eyebrow'): 'Модалка — eyebrow',
    ('site', 'lead_modal_title'): 'Модалка — заголовок',
    ('site', 'lead_modal_lead'): 'Модалка — опис',
    ('site', 'modal_close_aria'): 'Aria: закрити',
    ('site', 'service_modal_loading'): 'Завантаження модалки послуги',
    ('services', 'page_section_visible'): 'Показувати hero послуг',
    ('services', 'hero_badge'): 'Badge',
    ('services', 'hero_sub'): 'Підзаголовок',
    ('services', 'catalog_section_visible'): 'Показувати каталог',
    ('services', 'catalog_eyebrow'): 'Eyebrow каталогу',
    ('services', 'catalog_intro'): 'Вступ каталогу',
    ('services', 'catalog_card_more'): 'Текст кнопки картки',
    ('services', 'catalog_empty'): 'Порожній стан',
    ('services', 'process_section_visible'): 'Показувати процес',
    ('services', 'process_eyebrow'): 'Eyebrow процесу',
    ('services', 'process_title'): 'Заголовок процесу',
    ('services', 'process_intro'): 'Вступ процесу',
    ('services', 'cta_section_visible'): 'Показувати CTA',
    ('services', 'cta_eyebrow'): 'Eyebrow CTA',
    ('services', 'cta_title'): 'Заголовок CTA',
    ('services', 'cta_intro'): 'Вступ CTA',
    ('services', 'cta_form_title'): 'Заголовок форми',
    ('services', 'detail_badge'): 'Badge деталі',
    ('services', 'detail_deliverables_title'): 'Заголовок deliverables',
    ('services', 'detail_result_title'): 'Заголовок результату',
    ('services', 'detail_timeline_label'): 'Підпис термінів',
    ('services', 'modal_eyebrow'): 'Модалка — eyebrow',
    ('services', 'modal_deliverables_title'): 'Модалка — deliverables',
    ('services', 'modal_result_title'): 'Модалка — результат',
    ('services', 'modal_timeline_label'): 'Модалка — терміни',
    ('services', 'modal_cta'): 'Модалка — CTA',
    ('services', 'modal_full_page'): 'Модалка — повна сторінка',
    ('contacts', 'page_section_visible'): 'Показувати hero контактів',
    ('contacts', 'hero_badge'): 'Badge',
    ('contacts', 'hero_sub'): 'Підзаголовок',
    ('contacts', 'info_badge'): 'Badge колонки',
    ('contacts', 'info_title'): 'Заголовок колонки',
    ('contacts', 'label_phone'): 'Підпис телефону',
    ('contacts', 'label_email'): 'Підпис email',
    ('contacts', 'label_region'): 'Підпис регіону',
    ('contacts', 'email_copy_hint'): 'Підказка копіювання',
    ('contacts', 'email_copied'): 'Текст після копіювання',
    ('contacts', 'region_suffix'): 'Суфікс регіону',
    ('contacts', 'form_title'): 'Заголовок форми',
    ('contacts', 'form_subtext'): 'Підтекст форми',
    ('blog', 'page_section_visible'): 'Показувати hero блогу',
    ('blog', 'hero_badge'): 'Badge',
    ('blog', 'hero_sub'): 'Підзаголовок (якщо немає SEO description)',
    ('blog', 'load_more'): 'Кнопка «ще»',
    ('blog', 'empty'): 'Порожній стан',
    ('blog', 'share_title'): 'Поділитися',
    ('blog', 'seal_text'): 'Печатка — текст',
    ('blog', 'seal_sub'): 'Печатка — підпис',
    ('blog', 'watermark'): 'Водяний знак картки',
}

BLOCK_CONTENT_TYPES: dict[BlockKey, ContentTypeName] = {
    ('home', 'hero_image'): 'image',
    ('home', 'advantages_image'): 'image',
    ('site', 'logo_header'): 'image',
    ('site', 'logo_footer'): 'image',
}

BLOCK_FIELD_HELP: dict[BlockKey, str] = {
    (
        'home',
        'hero_image',
    ): (
        'Рекомендований розмір: 1920×823 px (співвідношення 21:9). '
        'Формат: JPG, PNG або WebP. Якщо фото більше або з іншим '
        'співвідношенням — воно обрізається по краях, щоб заповнити банер.'
    ),
    (
        'home',
        'hero_shade_visible',
    ): 'Темний градієнт поверх фото для кращої читабельності тексту.',
    (
        'home',
        'advantages_image',
    ): (
        'Фото під вступним текстом у лівій колонці. '
        'Формат: JPG, PNG або WebP. Зображення масштабується '
        'в межах колонки й не виходить за краї блоку.'
    ),
}

INLINE_KEYS: frozenset[BlockKey] = frozenset(
    {
        ('home', 'hero_brand'),
        ('home', 'hero_cta_label'),
        ('home', 'hero_cta_href'),
        ('home', 'hero_secondary_label'),
        ('home', 'hero_secondary_href'),
        ('home', 'audience_eyebrow'),
        ('home', 'audience_cta_label'),
        ('home', 'audience_cta_href'),
        ('home', 'services_eyebrow'),
        ('home', 'services_card_more'),
        ('home', 'services_footer_cta'),
        ('home', 'services_footer_href'),
        ('home', 'advantages_eyebrow'),
        ('home', 'blog_eyebrow'),
        ('home', 'blog_filter_all'),
        ('home', 'blog_filter_cases'),
        ('home', 'blog_filter_news'),
        ('home', 'blog_footer_cta'),
        ('home', 'lead_eyebrow'),
        ('home', 'lead_title'),
        ('site', 'brand_name'),
        ('site', 'brand_title'),
        ('site', 'nav_toggle_label'),
        ('site', 'nav_open_aria'),
        ('site', 'nav_aria'),
        ('site', 'nav_home_label'),
        ('site', 'nav_home_href'),
        ('site', 'nav_about_label'),
        ('site', 'nav_about_href'),
        ('site', 'nav_services_label'),
        ('site', 'nav_services_href'),
        ('site', 'nav_blog_label'),
        ('site', 'nav_blog_href'),
        ('site', 'nav_contacts_label'),
        ('site', 'nav_contacts_href'),
        ('site', 'nav_cta_label'),
        ('site', 'nav_cta_href'),
        ('site', 'footer_nav_heading'),
        ('site', 'footer_contacts_heading'),
        ('site', 'footer_messengers_heading'),
        ('site', 'footer_hours_prefix'),
        ('site', 'footer_policy_label'),
        ('site', 'footer_policy_href'),
        ('site', 'footer_madeby_label'),
        ('site', 'footer_madeby_url'),
        ('site', 'footer_nav_aria'),
        ('site', 'form_label_name'),
        ('site', 'form_label_phone'),
        ('site', 'form_label_email'),
        ('site', 'form_consent_prefix'),
        ('site', 'form_consent_link'),
        ('site', 'form_submit'),
        ('site', 'form_success_title'),
        ('site', 'lead_modal_eyebrow'),
        ('site', 'lead_modal_title'),
        ('site', 'modal_close_aria'),
        ('site', 'service_modal_loading'),
        ('services', 'hero_badge'),
        ('services', 'catalog_eyebrow'),
        ('services', 'catalog_card_more'),
        ('services', 'process_eyebrow'),
        ('services', 'process_title'),
        ('services', 'cta_eyebrow'),
        ('services', 'cta_form_title'),
        ('services', 'detail_badge'),
        ('services', 'detail_deliverables_title'),
        ('services', 'detail_result_title'),
        ('services', 'detail_timeline_label'),
        ('services', 'modal_eyebrow'),
        ('services', 'modal_deliverables_title'),
        ('services', 'modal_result_title'),
        ('services', 'modal_timeline_label'),
        ('services', 'modal_cta'),
        ('services', 'modal_full_page'),
        ('contacts', 'hero_badge'),
        ('contacts', 'info_badge'),
        ('contacts', 'info_title'),
        ('contacts', 'label_phone'),
        ('contacts', 'label_email'),
        ('contacts', 'label_region'),
        ('contacts', 'email_copy_hint'),
        ('contacts', 'email_copied'),
        ('contacts', 'region_suffix'),
        ('contacts', 'form_title'),
        ('blog', 'hero_badge'),
        ('blog', 'load_more'),
        ('blog', 'empty'),
        ('blog', 'share_title'),
        ('blog', 'seal_text'),
        ('blog', 'seal_sub'),
    }
)

MULTILINE_KEYS: frozenset[BlockKey] = frozenset(
    {
        ('home', 'hero_sub'),
        ('home', 'audience_intro'),
        ('home', 'audience_cta_text'),
        ('home', 'services_intro'),
        ('home', 'advantages_intro'),
        ('home', 'blog_intro'),
        ('home', 'lead_intro'),
        ('site', 'footer_tagline'),
        ('site', 'form_success_text'),
        ('site', 'lead_modal_lead'),
        ('services', 'hero_sub'),
        ('services', 'catalog_intro'),
        ('services', 'process_intro'),
        ('services', 'cta_intro'),
        ('contacts', 'hero_sub'),
        ('contacts', 'form_subtext'),
        ('blog', 'hero_sub'),
        ('blog', 'watermark'),
    }
)
